CREATE DATABASE IF NOT EXISTS UAS_BASDAT;
USE UAS_BASDAT;

CREATE TABLE users (
  user_id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  role VARCHAR(50),
  password_hash VARCHAR(255) NOT NULL,
  created_at DATE NOT NULL
);
